// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCojAJY5yp1ju2BqaKs5d3DQCXGoxFHa2Q',
    appId: '1:435750144342:web:f329f4a2f11f35c169eef7',
    messagingSenderId: '435750144342',
    projectId: 'iu-nav-bus-project-a2e12',
    authDomain: 'iu-nav-bus-project-a2e12.firebaseapp.com',
    storageBucket: 'iu-nav-bus-project-a2e12.appspot.com',
    measurementId: 'G-E7NFYXZFZV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmKajASl8tArJLvh0c38AY13E6PqE2Lsg',
    appId: '1:435750144342:android:482028854c26f7c069eef7',
    messagingSenderId: '435750144342',
    projectId: 'iu-nav-bus-project-a2e12',
    storageBucket: 'iu-nav-bus-project-a2e12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqPUrQjmW0JCKNJqvvN6thGZB3cvxzs5I',
    appId: '1:435750144342:ios:45eb85c37e6fc2a369eef7',
    messagingSenderId: '435750144342',
    projectId: 'iu-nav-bus-project-a2e12',
    storageBucket: 'iu-nav-bus-project-a2e12.appspot.com',
    iosBundleId: 'com.example.iuNavBus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqPUrQjmW0JCKNJqvvN6thGZB3cvxzs5I',
    appId: '1:435750144342:ios:5a63283361bd80d169eef7',
    messagingSenderId: '435750144342',
    projectId: 'iu-nav-bus-project-a2e12',
    storageBucket: 'iu-nav-bus-project-a2e12.appspot.com',
    iosBundleId: 'com.example.iuNavBus.RunnerTests',
  );
}
